//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlIndexConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ReorganizeIndexFragmentationThreshold {
            get {
                return ((int)(this["ReorganizeIndexFragmentationThreshold"]));
            }
            set {
                this["ReorganizeIndexFragmentationThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public long ReorganizeIndexMinimumSize {
            get {
                return ((long)(this["ReorganizeIndexMinimumSize"]));
            }
            set {
                this["ReorganizeIndexMinimumSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReorganizeIndexLobCompaction {
            get {
                return ((bool)(this["ReorganizeIndexLobCompaction"]));
            }
            set {
                this["ReorganizeIndexLobCompaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RebuildIndexFragmentationThreshold {
            get {
                return ((int)(this["RebuildIndexFragmentationThreshold"]));
            }
            set {
                this["RebuildIndexFragmentationThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public long RebuildIndexMinimumSize {
            get {
                return ((long)(this["RebuildIndexMinimumSize"]));
            }
            set {
                this["RebuildIndexMinimumSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RebuildIndexSortInTempDb {
            get {
                return ((bool)(this["RebuildIndexSortInTempDb"]));
            }
            set {
                this["RebuildIndexSortInTempDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RebuildIndexOnline {
            get {
                return ((bool)(this["RebuildIndexOnline"]));
            }
            set {
                this["RebuildIndexOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RebuildIndexMaxDop {
            get {
                return ((int)(this["RebuildIndexMaxDop"]));
            }
            set {
                this["RebuildIndexMaxDop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int RebuildIndexCommandTimeout {
            get {
                return ((int)(this["RebuildIndexCommandTimeout"]));
            }
            set {
                this["RebuildIndexCommandTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int ReorganizeIndexCommandTimeout {
            get {
                return ((int)(this["ReorganizeIndexCommandTimeout"]));
            }
            set {
                this["ReorganizeIndexCommandTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastConnectionString {
            get {
                return ((string)(this["LastConnectionString"]));
            }
            set {
                this["LastConnectionString"] = value;
            }
        }
    }
}
